/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arquicomp;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileWriter;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author B25201
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    
    String output="";
    
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableArchivos = new javax.swing.JTable();
        btnEliminarArchivos = new javax.swing.JButton();
        btnAgregarArchivo = new javax.swing.JButton();
        btnEjecutarHilos = new javax.swing.JButton();
        lblQuantum = new javax.swing.JLabel();
        lblM = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        txtQuantum = new javax.swing.JTextField();
        txtM = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        radioModoRapido = new javax.swing.JRadioButton();
        radioModoLento = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tableArchivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre de archivo", "Path", "Eliminar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableArchivos);

        btnEliminarArchivos.setLabel("Eliminar archivos seleccionados");
        btnEliminarArchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarArchivosActionPerformed(evt);
            }
        });

        btnAgregarArchivo.setLabel("Agregar archivo");
        btnAgregarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarArchivoActionPerformed(evt);
            }
        });

        btnEjecutarHilos.setLabel("Ejecutar hilos");
        btnEjecutarHilos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarHilosActionPerformed(evt);
            }
        });

        lblQuantum.setText("Quantum:");

        lblM.setText("m:");

        lblB.setText("b:");

        txtQuantum.setText("30");

        txtM.setText("1");

        txtB.setText("1");

        radioModoRapido.setSelected(true);
        radioModoRapido.setText("Modo rápido");
        radioModoRapido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioModoRapidoActionPerformed(evt);
            }
        });

        radioModoLento.setText("Modo lento");
        radioModoLento.setName(""); // NOI18N
        radioModoLento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioModoLentoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEjecutarHilos)
                        .addGap(149, 149, 149))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnAgregarArchivo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminarArchivos))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblQuantum)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(radioModoRapido)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(radioModoLento))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtQuantum, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(53, 53, 53)
                                    .addComponent(lblM)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblB)))
                            .addGap(18, 18, 18)
                            .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(63, 63, 63))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarArchivo)
                    .addComponent(btnEliminarArchivos))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioModoRapido)
                    .addComponent(radioModoLento))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantum)
                    .addComponent(lblM)
                    .addComponent(lblB)
                    .addComponent(txtQuantum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnEjecutarHilos)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarArchivoActionPerformed
        DefaultTableModel model = (DefaultTableModel) tableArchivos.getModel();
        
        JFileChooser chooser= new JFileChooser();
        chooser.setMultiSelectionEnabled(true);
        int choice = chooser.showOpenDialog(null);
        
        if (choice == JFileChooser.APPROVE_OPTION){
            File[] selectedFiles = chooser.getSelectedFiles();
            for(int i=0;i<selectedFiles.length;i++){
                File chosenFile = selectedFiles[i];
                model.addRow(new Object[]{chosenFile.getName(), chosenFile.getPath(), false});
            }
        }
    }//GEN-LAST:event_btnAgregarArchivoActionPerformed

    private void btnEliminarArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarArchivosActionPerformed
        DefaultTableModel model=(DefaultTableModel)tableArchivos.getModel();
        for(int i = 0; i<model.getRowCount(); i++) {
            if((boolean)model.getValueAt(i, 2)){
                model.removeRow(i);
            }
        }
    }//GEN-LAST:event_btnEliminarArchivosActionPerformed

    private void btnEjecutarHilosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarHilosActionPerformed
        // TODO add your handling code here:
        String modoLento="false";
        if(radioModoLento.isSelected()){
            modoLento="frlse";
        }
        
        String quantum=txtQuantum.getText();
        String m = txtM.getText();
        String b = txtB.getText();
        try{
            if(Integer.parseInt(quantum) > 0 && Integer.parseInt(m)>0 && Integer.parseInt(b)>0){
            
                jLabel4.setText("");
                String params[] = new String[tableArchivos.getRowCount()+5];
                params[0]="Main.exe";
                params[1]=modoLento;
                params[2]=quantum;
                params[3]=m;
                params[4]=b;
                for(int i=5;i<params.length;i++){
                    params[i]=(String)tableArchivos.getModel().getValueAt(i-5, 1);
                }
                for(int i=0;i<params.length;i++){
                    System.out.println(params[i]);
                }
                Process process = new ProcessBuilder(params).start();
                BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
                String line=null;
                //process.waitFor();
                while((line=reader.readLine()) != null){
                    output+=line+"\n";
                }
                File file = new File("log.txt");
                file.delete();
                file = new File("log.txt");
                FileWriter fw = new FileWriter(file);
            	PrintWriter pw = new PrintWriter(fw);
                pw.write(output + "\n" + "\r\n");
	    	pw.close();
                //javax.swing.JOptionPane.showMessageDialog(null, output, "Processors results", javax.swing.JOptionPane.INFORMATION_MESSAGE, null);
                new Results().setVisible(true);
                
            }
            else{
            jLabel4.setText("Asegúrese que todos los parámetros que ingresó son mayores a 0.");
            }
        }
        catch(Exception e){
            if(e.getClass().getSimpleName().equals("NumberFormatException")){
                jLabel4.setText("Asegúrese que los parámetros que ingresó son únicamente números.");
            }

        }
        
   
    }//GEN-LAST:event_btnEjecutarHilosActionPerformed

    private void radioModoRapidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioModoRapidoActionPerformed
        // TODO add your handling code here:
        if(!radioModoLento.isSelected()){
            radioModoRapido.setSelected(true);
        }
        radioModoLento.setSelected(false);
    }//GEN-LAST:event_radioModoRapidoActionPerformed

    private void radioModoLentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioModoLentoActionPerformed
        if(!radioModoRapido.isSelected()){
            radioModoLento.setSelected(true);
        }
        radioModoRapido.setSelected(false);
    }//GEN-LAST:event_radioModoLentoActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarArchivo;
    private javax.swing.JButton btnEjecutarHilos;
    private javax.swing.JButton btnEliminarArchivos;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblM;
    private javax.swing.JLabel lblQuantum;
    private javax.swing.JRadioButton radioModoLento;
    private javax.swing.JRadioButton radioModoRapido;
    private javax.swing.JTable tableArchivos;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtM;
    private javax.swing.JTextField txtQuantum;
    // End of variables declaration//GEN-END:variables
}
